# Generated by Django 3.0.2 on 2020-01-23 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpuinfo',
            name='ct',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
