# Generated by Django 3.0.2 on 2020-01-23 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_cpuinfo_ct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cpuinfo',
            old_name='ct',
            new_name='update_time',
        ),
    ]
