# Generated by Django 3.0.2 on 2020-01-23 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20200123_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='memoryinfo',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='solidstatedisk',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='cpuinfo',
            name='update_time',
            field=models.DateTimeField(default='2020-01-23 17:06:30', verbose_name='更新时间'),
        ),
    ]
